MvcBookStore/Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBookStore.Models;
using PagedList;
using PagedList.Mvc;

namespace MvcBookStore.Controllers
{
    public class BookStoreController : Controller
    {
        dbQLBansachDataContext data = new dbQLBansachDataContext();
        // GET: BookStore
        private List<SACH> LaySachMoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        //public ActionResult Index()
        //{
        //    var sachmoi = LaySachMoi(5);
        //    return View(sachmoi);
        //}
        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }
        public ActionResult Nhaxuatban()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);
        }
        public ActionResult Index(string searchString, int? page)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            ViewBag.Keyword = searchString;
            var book = data.SACHes.ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                book = book.Where(s => s.Tensach.Contains(searchString)).ToList();
                book.OrderByDescending(v => v.Masach);
                var finalList = book.ToPagedList(pageNum, pageSize);
                return View(finalList);
            }
            else
            {
                var sachmoi = LaySachMoi(15);
                return View(sachmoi.ToPagedList(pageNum, pageSize));
            }
        }
        public ActionResult SPTheochude(int id)
        {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }
        public ActionResult SPTheoNXB(int id)
        {
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach);
        }
        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes
                       where s.Masach == id
                       select s;
            return View(sach.Single());
        }
    }
}

MvcBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcBookStore/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">

            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("INDEX", "admin")">Trang chủ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("sanpham", "admin")">Quản lý chủ đề</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("nhaxuatban", "admin")">Quản lý nhà xuất bản</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("sach", "admin")">Quản lý sách</a>
                </li>
            </ul>

        </nav>
        <div class="tab-content">
            @RenderBody()
        </div>
    </div>
</body>
</html>

MvcBookStore/Views/Shared/_LayoutUser.cshtml
@using MvcBookStore.Models;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="~/Content/templatemo_style.css" rel="stylesheet" />
</head>
<body>
    <div id="templatemo_container">
        <div id="templatemo_menu">
            <ul>
                <li><a href="@Url.Action("index", "bookstore")" class="current"><img src="~/images/home.png" class="current" /> Trang chủ</a></li>
                <li><a href="#" class="current"><img src="~/images/contact.png" class="current" /> Liên hệ</a></li>
                @if (Session["Taikhoan"] == null)
                {
                    <li style="float: right"><a href="@Url.Action("dangky", "nguoidung")" class="current"><img src="~/images/login.png" class="current" /> Đăng ký</a></li>
                    <li style="float: right"><a href="@Url.Action("dangnhap", "nguoidung")" class="current"><img src="~/images/login.png" class="current" /> Đăng nhập</a></li>
                    <li style="float: right">@Html.Action("giohangpartial", "giohang")</li>
                }
                else
                {
                    dbQLBansachDataContext data = new dbQLBansachDataContext();
                    KHACHHANG kh = (KHACHHANG)(Session["Taikhoan"]);
                    <li style="float: right"><a href="@Url.Action("dangxuat", "nguoidung")" class="current"><img src="~/images/logout.png" class="current" /> Đăng xuất</a></li>
                    <li style="float: right"><font style="font-size: 12px; font-weight: bold; text-align: center; text-decoration: none; color: #fcf88e"><img src="~/images/user.png" class="current" /> Chào @kh.HoTenKH!</font></li>
                    <li style="float: right">@Html.Action("giohangpartial", "giohang")</li>
                }
            </ul>
        </div> <!-- end of menu -->

        <div id="templatemo_header">
            <div id="templatemo_special_offers">
                <p>
                    <span>25%</span> discounts for
                    purchase over $80
                </p>
                <a href="subpage.html" style="margin-left: 50px;">Read more...</a>
            </div>


            <div id="templatemo_new_books">
                <ul>
                    <li>Suspen disse</li>
                    <li>Maece nas metus</li>
                    <li>In sed risus ac feli</li>
                </ul>
                <a href="subpage.html" style="margin-left: 50px;">Read more...</a>
            </div>
        </div> <!-- end of header -->

        <div id="templatemo_content">

            <div id="templatemo_content_left">
                @Html.Action("Chude", "BookStore")
                @Html.Action("Nhaxuatban", "BookStore")

            </div> <!-- end of content left -->

            <div id="templatemo_content_right">

                @RenderBody()


                <a href="subpage.html"><img src="~/images/templatemo_ads.jpg" alt="ads" /></a>
            </div> <!-- end of content right -->

            <div class="cleaner_with_height">&nbsp;</div>
        </div> <!-- end of content -->

        <div id="templatemo_footer">

            <a href="subpage.html">Home</a> | <a href="subpage.html">Search</a> | <a href="subpage.html">Books</a> | <a href="#">New Releases</a> | <a href="#">FAQs</a> | <a href="#">Contact Us</a><br />
            Copyright © 2018 <a href="#"><strong>Huflit</strong></a> | <a href="http://www.iwebsitetemplate.com" target="_parent">Website Templates</a> by <a href="http://www.templatemo.com" target="_parent" title="free css templates">Free CSS Templates</a>
        </div>
        <!-- end of footer -->
        <!--  Free CSS Template www.templatemo.com -->
    </div> <!-- end of container -->
</body>
</html>